--
error:
  format: png
  img: /www/foo/cache/images/error.png
title: bdl
source_url: http://wms.alaskamapped.org/bdl?layers=bdl_low_res,bdl_mid_res,bdl_high_res&styles=&service=WMS&width=%d&format=image/jpeg&request=GetMap&height=%d&srs=EPSG:900913&version=1.1.1&bbox=%6.10f,%6.10f,%6.10f,%6.10f
tiles:
  y_size: 256
  x_size: 256
  x_count: 5
  y_count: 5
temp_area: ./tile_temp/
debug: false
storage_format: jpg
cache_dir:  /www/foo/cache/
base_extents:
  ymax: 20037508.3427892
  xmax: 20037508.3427892
  ymin: -20037508.3427892
  xmin: -20037508.3427892
label:
  size: 10
  text: "SDMI - GINA"
  color:
  - 0
  - 128
  - 0
  - 60
