--- 
tile_engines:
  conf_dir: "./conf.d/"
  mailer_config: &id001
    from: example@foo.edu
    to: example@foo.edu
    setup:
      :domain: foo.edu
      :address: foo.edu
controller:
  base_url: "/controller"
  ips_allowed:
    - 99.99.19.236
    - 0.0.0.0
  reload_action: "reload"
log: 
  info: true
  verbose: true
  debug: false
  quiet: false
  logdir: "./logs/"
esri:
  note: "something will go here someday - this is a placeholder."
http: 
  bind: 0.0.0.0
  base: /rest/
  host: tiles.foo.com
