
source 'https://rubygems.org'
gem 'curb'
gem 'daemons' 
gem 'fastthread'
gem 'highline'
gem 'json'
gem 'xml-simple'
gem 'json_pure'
gem 'rack'
gem 'mail'
gem 'rake'
gem 'rmagick', '~> 2.13.3'
gem 'puma', '2.9.0'
gem 'escape_utils'
gem 'haml'
gem 'rack-cache'
gem 'dalli'
