require 'rubygems'
#require "swiftcore/evented_mongrel"
#require "swiftcore/swiftiplied_mongrel"
#require 'mongrel'
require 'pp'
require 'lumber'
require 'tile_engine'
require 'handler'
require 'yaml'
require 'kml_generator'
require 'rack'
