error:
  format: png
  img: /hub/cache/production/images/error.png
title: aoos_bathy
source_url: http://wms.alaskamapped.org/cgi-bin/aoos_test.cgi?layers=aoos_bathy_sm&styles=&service=WMS&width=%d&format=image/png&request=GetMap&height=%d&srs=EPSG:900913&version=1.1.1&bbox=%6.10f,%6.10f,%6.10f,%6.10f
tiles:
  y_size: 256
  x_size: 256
  x_count: 3
  y_count: 3
temp_area: ./tile_temp/
debug: false
storage_format: png
cache_dir: ./cache/production/aoos_bath/
base_extents:
  ymax: 20037508.3427892
  xmax: 20037508.3427892
  ymin: -20037508.3427892
  xmin: -20037508.3427892
label:
  size: 10
  text: "AOOS - http://aoos.org"
  color:
  - 0
  - 128
  - 0
watermark:
  x_buffer: 30
  y_buffer: 30
  blending: 1
  image: "extras/aoos_logo3.png"
