--- 
tile_engines: 
  conf_dir: ./conf.d/
  mailer_config: &id001 
    from: cable@alaska.edu
    to: cable@alaska.edu
    setup: 
      :domain: gina.alaska.edu
      :address: dino.gi.alaska.edu
controller: 
  base_url: /snaptiles/controller
  ips_allowed: 
  - 137.229.19.236
  - 0.0.0.0
  reload_action: reload
log: 
  info: true
  verbose: true
  debug: false
  quiet: false
  logdir: ./logs/
kml: 
  root_url: /snaptiles/kml/
  mailer_config: *id001
  sets: 
    a1b.comp.prec.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.prec.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a1b.comp.prec.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.prec.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a1b.comp.prec.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.prec.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a1b.comp.temp.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.temp.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a1b.comp.temp.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.temp.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a1b.comp.temp.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a1b.comp.temp.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.prec.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.prec.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.prec.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.prec.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.prec.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.prec.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.temp.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.temp.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.temp.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.temp.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    a2.comp.temp.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/a2.comp.temp.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.prec.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.prec.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.prec.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.prec.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.prec.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.prec.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.temp.annual.2010-2019: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.temp.annual.2010-2019/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.temp.annual.2050-2059: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.temp.annual.2050-2059/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
    b1.comp.temp.annual.2090-2099: 
      tl: 
        x: -180.0
        y: 90.0
      br: 
        x: 180.0
        y: -90.0
      source: http://hippy.gina.alaska.edu/snaptiles/b1.comp.temp.annual.2090-2099/bbox/%.20f/%.20f/%.20f/%.20f/
      url: http://hippy.gina.alaska.edu/snaptiles/kml/%s/%.20f/%.20f/%.20f/%.20f
http: 
  bind: 0.0.0.0
  base: /snaptiles
