error:
  format: png
  img: /hub/cache/production/images/error.png
title: 
source_url: http://wms.alaskamapped.org/cgi-bin/aoos_test.cgi?layers=aoos_bathy_geo&styles=&service=WMS&width=%d&format=image/png&request=GetMap&height=%d&srs=EPSG:4326&version=1.1.1&bbox=%6.10f,%6.10f,%6.10f,%6.10f
tiles:
  y_size: 256
  x_size: 256
  x_count: 3
  y_count: 3
temp_area: ./tile_temp/
debug: false
storage_format: png
cache_dir: 
base_extents:
  ymax: 90.0
  xmax: 180.0
  ymin: -90.0
  xmin: -180.0
